### ISSUE TITLE
Direct to custom login page

### ISSUE THREAD

**Issue by HBiSoft** [luizbills/woo-force-authentification-before-checkout#12]
Hi Luiz. Thank you for your work on this plugin. 

Is it possible to redirect to a custom login page? for example `website.com/login` I assume it would have to be done here:

https://github.com/luizbills/woo-force-authentification-before-checkout/blob/2612de05d51b74f7ad46fda66f73cca2ad335022/woo-force-authentification-before-checkout.php#L37-L41

I'm not familiar with php at all. Your help would be greatly appreciated.

Thank you.
Hagen

**Comment by luizbills** [comment]
put this in your theme's `functions.php`:
```php
add_filter( 'wc_force_auth_login_page_url', function ( $url ) {
    return home_url( '/login' ); 
} );

**Comment by HBiSoft** [comment]
That works perfectly. Thank you very much.
