### ISSUE TITLE
after login?

### ISSUE THREAD

**Issue by rjcrosthwaite** [luizbills/woo-force-authentification-before-checkout#13]
Hi Luiz,

After login, I'm left on the account page. Is this the intention? I was expecting to arrive on the checkout page.

**Comment by luizbills** [comment]
After logged in, your my account url is `https://yoursite.com/myaccount?redirect_to_checkout` ?
If it doesn't have this query argument, then some other plugin is conflicting and removing this parameter.

**Comment by rjcrosthwaite** [comment]
Hi,

Thank you for getting back to me. I'll look into that.

Regards
________________________________
