### ISSUE TITLE
car empty after login redirect

### ISSUE THREAD

**Issue by tabakocuba** [luizbills/woo-force-authentification-before-checkout#14]
Hi, i'm using the url that you suggest, but also you say I need to deactivate some plugins but I have like 40.... can you help me with another advice

**Comment by luizbills** [comment]
My plugin just redirect from checkout to my account and redirect back to checkout after login. Just that!

I can't give support to 3rd party plugins. You need deactivate some plugins to find the conflict and ask for support to the developers of this other plugins.

**Comment by tabakocuba** [comment]
Hi, I do my research and the conflict is with the JETPACK plugin, this plugin is beneficial in several ways, just to let you know....I'm trying to go deeper into this matter

**Comment by luizbills** [comment]
I installed the [Jetpack](https://wordpress.org/plugins/jetpack/) with my plugin and works well. 

I added a product to the cart, I was redirected to my account page, logged in and my cart was not deleted. 

Are your sure that bug happens only when my plugin AND the jetpack plugin are activated together? Or its happens anytime when jetpack is running, even when my plugin is deactivated?

**Comment by tabakocuba** [comment]
i try with other plugin and happens the same thing, I always need ti have
jetpack uninstall and I don't want that

**Comment by luizbills** [comment]
Have your reported this in jetpack forum or repo? there is the right place for you to get support.
