### ISSUE TITLE
Custom login page before login

### ISSUE THREAD

**Issue by easebranding** [luizbills/woo-force-authentification-before-checkout#16]
Hey luiz can you tell me if the plugin supports custom login page?

**Comment by luizbills** [comment]
Hi. Copy-paste this snippet:

```php
add_filter( 'wc_force_auth_login_page_url', function () {
    return 'site.com/your-custom-login';
} );
```
https://github.com/luizbills/woo-force-authentification-before-checkout/blob/master/woo-force-authentification-before-checkout.php#L38
