### ISSUE TITLE
This little plugin saved me. But it would be nice...

### ISSUE THREAD

**Issue by anthonyfox** [luizbills/woo-force-authentification-before-checkout#19]
This little plugin saved me. But it would be nice if it could be set to be triggered or activated in the event that a product required registration, like a course. May a product number or class could trigger the detour to register or log in.

Just an idea.

**Comment by luizbills** [comment]
You can use the `wc_force_auth_redirect_to_account_page` hook filter to customize the default behavior. If you don't have the technical knowledge for this, I recommend hiring a developer you trust.
https://github.com/luizbills/woo-force-authentification-before-checkout/blob/master/woo-force-authentification-before-checkout.php#L66
