### ISSUE TITLE
Hello luiz, issue with plugin

### ISSUE THREAD

**Issue by luisberd2020** [luizbills/woo-force-authentification-before-checkout#2]
it was working fine but now send to error page.

i have 2 sites same name but one is .com.co and the other one is .us

this is the URL after plugin redirection

https://praiabydayanaraduran.com.co/my-account?redirect_to=https://praiabydayanaraduran.com.co/my-account/
the same on both sites, the URL of .com.co

Thanks for your time and effort

Luis Berdejo

**Comment by luisberd2020** [comment]
Hello Luiz, each site is hosted separated instances on aws. (differents accounts) it's not a issue of domains config. Thanks for your time

**Comment by luizbills** [comment]
This plugin don't put `?redirect_to=...`, maybe it is a conflict with another plugin.

**Comment by luisberd2020** [comment]
Hello again

Yes, i hace the plugin ok anther wp installation and it's fine. I'm gonna check plugins.

Thanks

Get Outlook para Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by luisberd2020** [comment]
Hello Luiz, the plugins has been deactivated and deleted but in login/register icon on this domain: https:/praiabydayanaraduran.us keeps sending to this url

praiabydayanaraduran.com.co<https://praiabydayanaraduran.com.co/my-account?redirect_to=https://praiabydayanaraduran.com.co/my-account/>/my-account?redirect_to=praiabydayanaraduran.com.co<https://praiabydayanaraduran.com.co/my-account?redirect_to=https://praiabydayanaraduran.com.co/my-account/>/my-account/

Where can I delete all registers or data from your plugin???

there no cookies I am trying in several devices.

if you can check please enter domain https://praiabydayanaraduran.us and click on user icon on right side of header.


Thanks for your time

Luis Berdejo

________________________________

**Comment by luizbills** [comment]
> Where can I delete all registers or data from your plugin???
This plugin don't store anything in database.

> Hello Luiz, the plugins has been deactivated and deleted but in login/register icon on this domain: https:/praiabydayanaraduran.us keeps sending to this url
This plugin redirect only if you come from checkout page.
