### ISSUE TITLE
Allow checkout as guest? (maybe)

### ISSUE THREAD

**Issue by luizbills** [luizbills/woo-force-authentification-before-checkout#6]

**Comment by highkey1** [comment]
How to add option to 'continue as a guest' with the customer providing an email? 
Thank you!

**Comment by luizbills** [comment]
> How to add option to 'continue as a guest' with the customer providing an email? Thank you!

There is no option that allow this in the plugin.

**Comment by highkey1** [comment]
emailed you with a question. Thanks
